replicaCount: 1

image:
  repository: rollout
  pullPolicy: Never
  tag: latest

serviceAccount:
  create: true

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 500m
    memory: 128Mi
