apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rollout.fullname" . }}
  labels:
    {{- include "rollout.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rollout.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rollout.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "rollout.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
